---
- hosts: localhost
  tasks:
    - name: generate secret
      ansible.builtin.shell: date +%s | sha256sum | base64 | head -c 32 ; echo

      register: command_output
      changed_when: false

    - name: print command_output
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"

- hosts: localhost
  tasks:
    - name: print paswd
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"
