---
- hosts: web-server1
  name: Example3
  tasks:
    - name: Stop secret
      ansible.builtin.shell: set -o pipefail && date +%s | sha256sum | base64 | head -c 32 ; echo
      args:
        executable: /bin/bash
      register: command_output
      changed_when: false

    - name: Print command_output
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"

- hosts: web-server2
  name: Example3-2
  tasks:
    - name: Print paswd
      ansible.builtin.debug:
        msg: "Secret password is {{ command_output.stdout }}"
