---
- hosts: all
  become: true
  name: Example2
  tasks:

    - name: Update Debian
      ansible.builtin.apt:
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Update RedHat
      ansible.builtin.yum:
        update_cache: true
      when: ansible_os_family == 'RedHat'


- hosts: web-server1
  become: true
  name: Example2-1
  tasks:
    - name: Install apache2
      ansible.builtin.package:
        name: apache2
        state: present

    - name: Start apache2
      ansible.builtin.service:
        name: apache2
        state: started

- hosts: web-server2
  become: true
  name: Example2-2
  tasks:
    - name: Install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
