---
- hosts: web-server1
  become: true
  name: example2-1
  tasks:
    - name: Stop apache2
      ansible.builtin.service:
        name: apache2
        state: stopped

- hosts: web-server2
  become: true
  name: example2-1-2
  tasks:
    - name: Stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
