---
- hosts: web-server1
  tasks:
    - name: generate secret
      shell: date +%s | sha256sum | base64 | head -c 32 ; echo
      register: command_output

    - name: command_output
      debug:
        msg: "Secret password is {{ command_output.stdout }}"

    - name: Add command_output to dummy host
      add_host:
        name: "command_output_holder"
        paswd: "{{ command_output.stdout }}"

    - name: print hostvars
      debug:
        msg: "Secret password is {{ hostvars['command_output_holder']['paswd'] }}"

- hosts: web-server2
  tasks:
    - name: print paswd
      debug:
        msg: "paswd is {{ hostvars['command_output_holder']['paswd'] }}"