---
- hosts: web-server1
  become: true
  tasks:

    - ansible.builtin.service:
        name: apache2
        state: stopped

- hosts: web-server2
  become: true
  tasks:

     - ansible.builtin.service:
         name: nginx
         state: stopped
