name: test postman files
on: [push]

jobs:
  test-postman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker
      run: |
        docker run -d -p 8080:80  nginx && \
          docker ps && sleep 1

    - name: "Check files existence"
      uses: andstor/file-existence-action@v2
      with:
        files: "sources/collection.json,sources/environment.json"
        fail: true

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@master
      with:
        collection: sources/collection.json
        environment: sources/environment.json
        reporters: cli
        suppressExitCode: true


    - name: Check if we failed
      id: fail-check
      shell: bash
      env:
        JSON_DOC: ${{ steps.run-newman.outputs.summary }}
      run: |
        printf '%s\n' "$JSON_DOC" > summary.json
        cat summary.json
        if grep -q Collection summary.json; then
          echo "failed=false" >> $GITHUB_OUTPUT;
        else
          echo "failed=true" >> $GITHUB_OUTPUT;
        fi

    - name: fail if empty
      if: ${{ steps.fail-check.outputs.failed == 'true' }}
      run: exit 1